name: Deploy Laravel Vite to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Vite (static assets)
        run: npm run build

      - name: Copy files to deploy branch
        run: |
          cp -r dist ../deploy
          cd ../deploy
          echo 'hamztech.my.id' > dist/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ../deploy/dist
          publish_branch: gh-pages
